export default {
  UPDATE_ACCESS_CODE: "REGISTER/UPDATE_ACCESS_CODE",
  DELAY_ACCESS_CODE: "REGISTER/DELAY_ACCESS_CODE",
  UPDATE_TAB: "HOME/UPDATE_TAB",
  UPDATE_SPLASH: "SPLASH/UPDATE_SPLASH",
  UPDATE_LOGIN: "LOGIN/UPDATE_LOGIN",
  UPDATE_LIBRARY: "PHOTO_LIBRARY/UPDATE_LIBRARY",
  UPDATE_SCROLLREF: "LANDING/UPDATE_SCROLLREF",
};
