const Images = {
  Logo: require("../Assets/Images/Logo.png"),
  Background: require("../Assets/Images/Background.png"),
  Lionstein_holding_glasses: require("../Assets/Images/Lionstein-holding-glasses.png"),
  MissChievous_Bouncing_On_Tail: require("../Assets/Images/MissChievous-Bouncing-On-Tail.png"),
  Penny_Waving: require("../Assets/Images/Penny-Waving.png"),
  Bubbles_Waving: require("../Assets/Images/Bubbles-Waving.png"),
  Testimonial_Base: require("../Assets/Images/Testimonial-Base.png"),
  Colen_Bubble: require("../Assets/Images/Colen-Bubble.png"),
  back_icon: require("../Assets/Images/back-icon.png"),
  Eye_icon: require("../Assets/Images/Eye-icon.png"),
  character_Description: require("../Assets/Images/character-Description.png"),
  Cancel_Icon: require("../Assets/Images/Cancel-Icon.png"),
  Dropdown_icon: require("../Assets/Images/Dropdown-icon.png"),
  Confirmation_check_Icon: require("../Assets/Images/Confirmation_check_Icon.png"),
  Lock_Graphic: require("../Assets/Images/Lock_Graphic.png"),
  Location_Graphic: require("../Assets/Images/Location_Graphic.png"),
  Search_Icon: require("../Assets/Images/Search_Icon.png"),
  Location_icon: require("../Assets/Images/Location_icon.png"),
  History_Icon: require("../Assets/Images/History_Icon.png"),
  Location_icon_Grey: require("../Assets/Images/Location_icon_Grey.png"),
  Distance_Pin_small: require("../Assets/Images/Distance_Pin_small.png"),
  Lcation_Pin_small: require("../Assets/Images/Lcation_Pin_small.png"),
  Phone_small: require("../Assets/Images/Phone_small.png"),
  any: require("../Assets/Images/any.jpg"),
  Phone_Icon: require("../Assets/Images/Phone_Icon.png"),
  Hamburger: require("../Assets/Images/Hamburger.png"),
  Notification_Icon: require("../Assets/Images/Notification_Icon.png"),
  Filter_Icon: require("../Assets/Images/Filter_Icon.png"),
  Elipsis: require("../Assets/Images/Elipsis.png"),
  Announcement_Icon: require("../Assets/Images/Announcement_Icon.png"),
  Announcement_light: require("../Assets/Images/Announcement_light.png"),
  Drop_Down_icon: require("../Assets/Images/Drop_Down_icon.png"),
  Home_Active: require("../Assets/Images/Home_Active.png"),
  attendance_Inactive: require("../Assets/Images/attendance_Inactive.png"),
  Photo_Library: require("../Assets/Images/Photo_Library.png"),
  Absence_Inactive: require("../Assets/Images/Absence_Inactive.png"),
};

export default Images;
