const Images = {
  Logo: require("../Assets/Images/Logo.png"),
  Background: require("../Assets/Images/Background.png"),
  Lionstein_holding_glasses: require("../Assets/Images/Lionstein-holding-glasses.png"),
  MissChievous_Bouncing_On_Tail: require("../Assets/Images/MissChievous-Bouncing-On-Tail.png"),
  Penny_Waving: require("../Assets/Images/Penny-Waving.png"),
  Bubbles_Waving: require("../Assets/Images/Bubbles-Waving.png"),
  Testimonial_Base: require("../Assets/Images/Testimonial-Base.png"),
  Colen_Bubble: require("../Assets/Images/Colen-Bubble.png"),
  back_icon: require("../Assets/Images/back-icon.png"),
  Eye_icon: require("../Assets/Images/Eye-icon.png"),
  character_Description: require("../Assets/Images/character-Description.png"),
  Cancel_Icon: require("../Assets/Images/Cancel-Icon.png"),
  Dropdown_icon: require("../Assets/Images/Dropdown-icon.png"),
  Confirmation_check_Icon: require("../Assets/Images/Confirmation_check_Icon.png"),
  Lock_Graphic: require("../Assets/Images/Lock_Graphic.png"),
  Location_Graphic: require("../Assets/Images/Location_Graphic.png"),
  Search_Icon: require("../Assets/Images/Search_Icon.png"),
  Location_icon: require("../Assets/Images/Location_icon.png"),
  History_Icon: require("../Assets/Images/History_Icon.png"),
  Location_icon_Grey: require("../Assets/Images/Location_icon_Grey.png"),
  Distance_Pin_small: require("../Assets/Images/Distance_Pin_small.png"),
  Lcation_Pin_small: require("../Assets/Images/Lcation_Pin_small.png"),
  Phone_small: require("../Assets/Images/Phone_small.png"),
};

export default Images;
