export default {
  SPLASH: "Splash",
  LANDING_PAGE: "LandingPage",
  LOGIN: "Login",
  FIND_SCHOOL: "FindSchool",
  REGISTER: "Register",
  ACCESS_CODE_VERIFICATION: "AccessCodeVerification",
  CREATE_PASSWORD: "CreatePassword",
  REQUEST_NEW_CODE: "RequestNewCode",
  RESET_PASSWORD_EMAIL: "ResetPasswordEmail",
  PASSWORD_RESET_CODE: "PasswordResetCode",
  RESET_PASSWORD: "ResetPassword",
  NEARBY_SCHOOL: "NearbySchool",
  SCHOOL_LISTING: "SchoolListing",
  SCHEDULE_TOUR: "ScheduleTour",
  DATE_TIME_SCHEDULE: "DateTimeSchedule",
  NEED_HELP: "NeedHelp",
  HOME: "Home",
  ATTENDANCE: "Attendance",
  PHOTO_LIBRARY: "Photo Library",
  ABSENCE: "Absence",
  AUTH_NAVIGATOR: "AuthNavigator",
  MODAL: "Modal",
  RESEND_CODE_MODAL: "ResendCodeModal",
  CREATE_PASSWORD_MODAL: "CreatePasswordModal",
  TAB_NAVIGATOR: "TabNavigator",
  GALLERY_DETAILS: "GalleryDetails",
  CREATE_ABSENCE: "CreateAbsence",
  PROFILE: "Profile",
  CHAT: "Chat",
  ANNOUNCEMENT: "Announcement",
  SETTINGS: "Settings",
  QOD: "QOD",
  EVENTS: "Events",
  CLASSROOM_SCHEDULE: "ClassroomSchedule",
  STATEMENTS: "Statements",
  REFERRAL: "Referral",
  TESTIMONIALS: "Testimonials",
  ABSENCE_NOTIFICATION_MODAL: "AbsenceNotificationModal",
  FILTER_MODAL: "FilterModal",
  SHARE_MODAL: "ShareModal",
  ACTIVITY_MODAL: "ActivityModal",
  LOGOUT_MODAL: "LogoutModal",
  BASIC_DETAILS: "Basic Details",
  MY_CHILDREN: "My Children",
  TOP_TAB_NAVIGATOR: "TopTabNavigator",
  CONTACT_MODAL: "ContactModal",
  CHILD_MODAL: "ChildModal",
  HOME_CHILD_MODAL: "HomeChildModal",
  ENTER_PASSWORD: "EnterPassword",
};
