import LocalizedStrings from "react-native-localization";

const Strings = new LocalizedStrings({
  en: {
    login: "Login",
    find_nearby_school: "Find Nearby School",
    need_help: "Need Help ?",
    Need_Help: "Need Help",
    testimonialtext:
      "“This is a great app for parents, especially in today’s busy schedule. This is just the app we need to relax ourselves while we are at work”",
    testimonialAuthor: "- Maggie James",
    testimonialCentre: "TLE @ Spring",
    under_development: "Under Development! Please try again Later",
    proceed: "Proceed",
    register: "Register",
    please_enter_email_and_password:
      "Please enter your registered email\nand Password",
    Parent_email: "Parent's Email",
    password: "Password",
    forgot_password: "Forgot Password ?",
    is_incorrect: " is incorrect",
    Email: "Email",
    Bubbles: "Bubbles",
    Lionstein: "Lionstein",
    Penny_Polite: "Penny Polite",
    Miss_Chievous: "Miss Chievous",
    bubbleMsg:
      "Our lovable friend who takes you on a daily adventure that makes kids happy to learn, play, and grow.",
    lionMsg:
      "Our wise and creative scientist who makes science fun and exciting.",
    pennyMsg:
      "Our well-mannered etiquette coach demonstrates the importance of being helpful, honest, and kind.",
    missMsg:
      "Our spunky monkey keeps kids active to promote a strong body and mind through sports and movement.",
    please_enter_email_and_centre:
      "Please enter your registered email and centre name",
    choose_centre: "Choose Centre",
    select_centre: "Select Centre",
    Access_Code_Verification: "Access Code Verification",
    Welcome: "Welcome ",
    please_enter_code: "Please enter the 4 digit access code\nreceived on ",
    wrong_code: "Entered Incorrect Code ! Please Try Again",
    Please_Fill_All_Boxes: "Please Fill All Boxes !",
    verify: "Verify",
    didnt_receive_code: "Didn’t receive access code ?",
    Request_New: "Request New",
    Request_New_Access_Code: "Request New Access Code",
    hello: "Hello",
    enter_phone_and_email:
      "Please enter your phone number to get new verification code.",
    parentPhone: "Parent’s Phone Number",
    phone_number: "Phone No.",
    Resent_Access_Code: "Resend Access Code",
    I_have_Access_Code: "I Already Have An Access Code",
    acsess_code_confirm:
      "New Access Code will be sent to your email in a while.",
    ok: "OK",
    Create_Password: "Create Password",
    create_password_content:
      "Please create a password to login to\nShow N Tell",
    Confirm_Password: "Confirm Password",
    Continue: "Continue",
    Password_successfully_created: "Password successfully created",
    Back_to_Login: "Back to Login",
    enter_email_passowrd_link:
      "Enter your registered email ID to receive\npassword reset link",
    Reset_Password: "Reset Password",
    Enter_Password_Reset_Code: "Enter Password Reset Code",
    Enter_New_Password: "Enter New Password",
    Confirm_New_Password: "Confirm New Password",
    Nearby_School: "Nearby School",
    Nearby_Schools: "Nearby Schools",
    Allow_Location_Access: "Allow Location Access",
    to_locate_schools:
      "To locate schools near you, enable location\nfrom settings or enter location manually.",
    Enable_Location_Access: "Enable Location Access",
    Select_Location_Manually: "Select Location Manually",
    Search_placeholder: "Search by City or Address",
    Use_my_location: "Use my current location",
    Recent_Searches: "Recent Searches",
    Choose_a_Center: "Choose a Center",
    Get_Directions: "Get Directions",
    Schedule_a_Tour: "Schedule a Tour",
    Please_select_date_time: "Please select date & time for your tour.",
    School_Name: "School Name",
    Next: "Next",
    Or: "Or",
    general_information: "I want only general information",
    Parent_Name: "Parent’s Name",
    Parent_First_Name: "Parent’s First Name",
    Parent_Last_Name: "Parent’s Last Name",
    Zip_Code: "Zip Code",
    First_Child_Name: "First Child Name",
    First_Child_DOB: "First Child Date of Birth",
    Second_Child_Name: "Second Child Name",
    Second_Child_DOB: "Second Child Date of Birth",
    Third_Child_Name: "Third Child Name",
    Third_Child_DOB: "Third Child Date of Birth",
    Fourth_Child_Name: "Fourth Child Name",
    Fourth_Child_DOB: "Fourth Child Date of Birth",
    Fifth_Child_Name: "Fifth Child Name",
    Fifth_Child_DOB: "Fifth Child Date of Birth",
    Name: "Name",
    DOB: "D.O.B",
    Add_Second_Child: "+ Add Second Child",
    Add_Third_Child: "+ Add Third Child",
    Add_Fourth_Child: "+ Add Fourth Child",
    Add_Fifth_Child: "+ Add Fifth Child",
    Schedule_Tour: "Schedule Tour",
    tour_success: "Your tour has been\nsuccessfully scheduled.",
    How_can_we_help_you: "How can we help you ?",
    Submit: "Submit",
    ticket_submitted: "Your support ticket has been\nsuccessfully submitted",
    Search: "Search",
    lunch_time: "Lunch Time",
    lunch_description:
      "This will help Alex in getting along with other children and importance of eating together.",
    Announcement: "Announcement",
    Announcements: "Announcements",
    anonsmtDescription:
      "Parent workshop has been conducted in the school premisis on 07th February. Make sure all of you attent the workshop from 10AM onwards.",
    Question_of_the_Day: "Question of the Day",
    QOD_description: "Ask Alex, what did he learn about dinosaure today ?",
    QOD_category: "Daily Activity • Literacy • GK",
    We_did_it: "We did it",
    I_did_it: "I did it",
    Chat: "Chat",
    QOD_label: "Question of the Day",
    Events: "Events",
    Classroom_Schedule: "Classroom Schedule",
    Statements: "Statements",
    Referral: "Referral",
    Referrals: "Referrals",
    Testimonials: "Testimonials",
    Settings: "Settings",
    Logout: "Logout",
    Attendance: "Attendance",
    View_by_Date: "View by Date",
    View_by_Month: "View by Month",
    Absence_Notification: "Absence Notification",
    From: "From",
    To: "To",
    at: " at ",
    Done: "Done",
    Filter: "Filter",
    Share: "Share",
    Save_to_Photo_Library: "Save to Phone",
    Cancel: "Cancel",
    logout_msg: "Are you sure,\nyou want to log out ?",
    Yes_Logout: "Yes, Logout",
    No: "No",
    Photo_Library: "Photo Library",
    lunch_name: "Why Lunch activity is important for children ?",
    lunch_msg:
      "This will help your children in getting along with rest of the kids, importance of eating together and also inculcate the basic eating manners, the different taste of food as well as learning names of different dishes.",
    Absence_Notifications: "Absence Notifications",
    Create_Absence_Notification: "Create Notification",
    Edit_Absence_Notification: "Edit Notification",
    set_DOB: "Set Date of Birth",
    Bob_Parish: "Mr. Bob Parish",
    Please_check_this: "Please check this out.",
    Alex_doing_Lunch: "Alex doing Lunch",
    apply_leave_on_time:
      "Please fill out the form below if your child will be unable to attend",
    Number_of_Days: "Number of Days",
    Reason_for_absence: "Reason for absence",
    Update: "Update",
    absence_submit_msg:
      "Your absence notification has been successfully submitted",
    absence_update_msg:
      "Your absence notification has been successfully updated",
    image_saved: "Image saved to gallery successfully!",
    My_Profile: "My Profile",
    Contact_Details: "Contact Details",
    Address_Details: "Address Details",
    Activity_Preferences: "Activity Preferences",
    Receive_Daily_Emails: "Receive Daily Emails",
    Out_of_City: "Out of City",
    Not_Well: "Not Well",
    Other: "Other",
    Phone_Number: "Phone Number",
    Mobile_Number: "Mobile Number",
    Other_Number: "Other Number",
    Medical_Information: "Medical Information",
    Teachers_Information: "Teacher’s Information",
    Balance: "Balance :",
    Date_Range: "Date Range",
    Clear: "Clear",
    to: " to ",
    Download_Statement: "Download Statement",
    Class_Schedule: "Class Schedule",
    Email_error: "Email is incorrect",
    Email_empty: "Email can't be empty",
    Password_mismatch: "Password dosen't match with new password",
    Password_Error:
      "Password should contain atleast 1 capital letter, 1 numeral and 1 special symbol",
    Password_length: "Password must be of atleast 8 characters",
    Password_Incorrect: "Password is incorrect",
    Phone_error: "Phone no. is incorrect",
    Phone_Empty: "Phone no. can't be empty",
    Permission_denied: "Please allow to access your Location from Settings",
    Name_error: "Name should contain characters only",
    Name_empty: "Name can't be empty",
    Zipcode_error: "Zipcode is incorrect",
    SchoolName_error: "Please select atleast 1 center",
    Device: "Device",
    Application: "Application",
    Remove_Child: "Remove Child",
    Chat_Room: "Chat Room",
    Write_here: "Write here",
    Chat_warning:
      "Responses to these messages may be delayed. For any critical issues, please call the center directly.",
    No_Internet: "No Internet! Please check your Internet Connection",
    Miles: "Miles",
    No_data_Found: "No Data Found",
    Timeout_error: "Response timeout! Please try again later",
    Select_School: "Select School",
    Enter_password: "Enter Password",
    Please_enter_password: "Please enter your Password here",
    Please_On_GPS: "Please switch your GPS ON to access your location",
    Unknown_error: "Unknown Error",
    Select_Date: "Select Date",
    View_Slots: "View Slots",
    Preferred_slot: "Please select a prefered time slot",
    DOB_incorrect: "DOB can't be empty",
    No_Location_Found: "No Location Found",
    Home_Feed_Options: "Home Feed Options",
    Reset: "Reset",
    Apply: "Apply",
    Activity_Category: "Activity Category",
    Date: "Date",
    Activity_Types: "Activity Types",
    General_Info: "Get More Info",
    Activities: "Activities",
    In_Time: "In Time",
    Out_Time: "Out Time",
    Not_Available: "Not Available",
    EmptyActivityType: "Please select atleast 1 Activity Type",
    invalidDate: `Please change the date ! To Date can't be less than From date`,
    Category_Unavailable: "No Category or Activity Found!",
    Testimonials_unavailable: "Testimonials Unavailable!",
    Address1: "Address 1",
    Address2: "Address 2",
    City: "City",
    State: "State",
    Camera: "Camera",
    Gallery: "Gallery",
    Notification: "Notification",
    Acknowledge: "Acknowledge",
    Activity_without_image: "Activities with photo only",
    About: "About",
    Terms_of_Service: "Terms of Service",
    Change_Password: "Change Password",
    Old_Password: "Old Password",
    New_Password: "New Password",
    All_Notifications: "All Notifications",
    Password_Conditions:
      "Password must have :\n• A minimal length of 8 characters\n• At least one capital letter\n• At least one numeral\n• At least one punctuation mark\n• Password should not match username\n• Password should not match the last 5 entered passwords",
    Add_Testimonials: "Add a Testimonial",
    Your_opinion_matters: "Your opinion matters",
    Thanks_Opinion:
      "Thank you so much for using our application and services. We would like to know your experience.",
    Description_optional: "Description",
    Password_Updated: "Your password has been\nsuccessfully updated",
    Testimonial_Success: "Your Testimonial has been successfully submitted",
    Thank_You: "Thank You !",
    Referral_Success:
      "Your referral has been successfully submitted to the Admin.",
    Sharing: "Sharing...",
  },
});
export default Strings;
