import LocalizedStrings from "react-native-localization";

const Strings = new LocalizedStrings({
  en: {
    login: "Login",
    find_nearby_school: "Find Nearby School",
    need_help: "Need Help ?",
    Need_Help: "Need Help",
    testimonialtext:
      "“This is a great app for parents, especially in today’s busy schedule. This is just the app we need to relax ourselves while we are at work”",
    testimonialAuthor: "- Maggie James",
    testimonialCentre: "TLE @ Spring",
    under_development: "Under Development! Please try again Later",
    proceed: "Proceed",
    register: "Register",
    please_enter_email_and_password:
      "Please enter your registered email\nand Password",
    Parent_email: "Parent's Email",
    password: "Password",
    forgot_password: "Forgot Password ?",
    is_incorrect: " is incorrect",
    Email: "Email",
    Bubbles: "Bubbles",
    Lionstein: "Lionstein",
    Penny_Polite: "Penny Polite",
    Miss_Chievous: "Miss Chievous",
    bubbleMsg:
      "Our lovable friend who takes you on a daily adventure that makes kids happy to learn, play, and grow.",
    lionMsg:
      "Our wise and creative scientist who makes science fun and exciting.",
    pennyMsg:
      "Our well-mannered etiquette coach demonstrates the importance of being helpful, honest, and kind.",
    missMsg:
      "Our spunky monkey keeps kids active to promote a strong body and mind through sports and movement.",
    please_enter_email_and_centre:
      "Please enter your registered email and centre name",
    choose_centre: "Choose Centre",
    select_centre: "Select Centre",
    Access_Code_Verification: "Access Code Verification",
    Welcome: "Welcome",
    please_enter_code: "Please enter the 4 digit access code\nreceived on ",
    wrong_code: "Entered Incorrect Code ! Please Try Again",
    Please_Fill_All_Boxes: "Please Fill All Boxes !",
    verify: "Verify",
    didnt_receive_code: "Didn’t receive access code ?",
    Request_New: "Request New",
    Request_New_Access_Code: "Request New Access Code",
    hello: "Hello",
    enter_phone_and_email:
      "Please enter your phone number along with\nyour email to get new verification code.",
    parentPhone: "Parent’s Phone Number",
    phone_number: "Phone No.",
    Resent_Access_Code: "Resent Access Code",
    I_have_Access_Code: "I have Access Code",
    acsess_code_confirm:
      "New Access Code will be sent to\nyour phone number and email\nin a while.",
    ok: "OK",
    Create_Password: "Create Password",
    create_password_content:
      "Create password which you can use to login to this application from next time onwards.",
    Confirm_Password: "Confirm Password",
    Continue: "Continue",
    Password_successfully_created: "Password successfully created",
    Back_to_Login: "Back to Login",
    enter_email_passowrd_link:
      "Enter your registered email ID to receive\npassword reset link",
    Reset_Password: "Reset Password",
    Enter_Password_Reset_Code: "Enter Password Reset Code",
    Enter_New_Password: "Enter New Password",
    Confirm_New_Password: "Confirm New Password",
    Nearby_School: "Nearby School",
    Nearby_Schools: "Nearby Schools",
    Allow_Location_Access: "Allow Location Access",
    to_locate_schools:
      "To locate schools near you, enable location\nfrom settings or enter location manually.",
    Enable_Location_Access: "Enable Location Access",
    Select_Location_Manually: "Select Location Manually",
    Search_placeholder: "Search by City or Address",
    Use_my_location: "Use my current location",
    Recent_Searches: "Recent Searches",
    Choose_a_Center: "Choose a Center",
    Get_Directions: "Get Directions",
    Schedule_a_Tour: "Schedule a Tour",
    Please_select_date_time: "Please select date & time for your tour.",
    School_Name: "School Name",
    Next: "Next",
    Or: "Or",
    general_information: "I want only general information",
    Parent_Name: "Parent’s Name",
    Zip_Code: "Zip Code",
    First_Child_Name: "First Child Name",
    First_Child_DOB: "First Child Date of Birth",
    Name: "Name",
    DOB: "D.O.B",
    Add_Second_Child: "+ Add Second Child",
    Schedule_Tour: "Schedule Tour",
    tour_success: "Your tour has been\nsuccessfully scheduled.",
    How_can_we_help_you: "How can we help you ?",
    Submit: "Submit",
    ticket_submitted: "Your support ticket has been\nsuccessfully submitted",
    Search: "Search",
    lunch_time: "Lunch Time",
    lunch_description:
      "This will help Alex in getting along with other children and importance of eating together.",
    Announcement: "Announcement",
    anonsmtDescription:
      "Parent workshop has been conducted in the school premisis on 07th February. Make sure all of you attent the workshop from 10AM onwards.",
    Question_of_the_Day: "Question of the Day",
    QOD_description: "Ask Alex, what did he learn about dinosaure today ?",
    QOD_category: "Daily Activity • Literacy • GK",
    We_did_it: "We did it",
    I_did_it: "I did it",
    Chat: "Chat",
    QOD_label: "Question of the Day",
    Events: "Events",
    Classroom_Schedule: "Classroom Schedule",
    Statements: "Statements",
    Referral: "Referral",
    Testimonials: "Testimonials",
    Settings: "Settings",
    Logout: "Logout",
    Attendance: "Attendance",
    View_by_Date: "View by Date",
    View_by_Month: "View by Month",
    Absence_Notification: "Absence Notification",
    From: "From",
    To: "To",
    Done: "Done",
    Filter: "Filter",
  },
});
export default Strings;
